name: Anushtha Kalia
bio: Undergrad @ CIC, University of Delhi
description: A blog about technology and stuff related
external-image: 'false'
picture: assets/images/profile.jpg
resume: true
resume-external: 'false'
resume-url: assets/Anushtha_Kalia_resume.pdf
url: 'https://anushthakalia.github.io'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - project
linkedin: anushthakalia
github: anushthakalia
email: anushthakalia@gmail.com
authors:
  anushthakalia:
    name: Anushtha Kalia
    bio: 'Information Technology & Math major @ CIC, University of Delhi'
    external-image: false
    picture: assets/images/profile.jpg
    twitter: anushthakalia
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/james.jpg
    twitter: jamesfoster
width: normal
projects: true
about: true
blog: false
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
